github:
  prebuilds:
    branches: true
gitConfig:
  alias.st: status
tasks:
  - before: |
      brew install poetry starship black
      echo 'eval "$(starship init bash)"' >> /home/gitpod/.bashrc
      poetry config virtualenvs.in-project true
    init: poetry install
    command: poetry shell
