github:
  prebuilds:
    branches: true
gitConfig:
  alias.st: status
image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      poetry config virtualenvs.in-project true
      poetry install
      gp sync-done backend
vscode:
  extensions:
    - ms-python.python
