[tool.poetry]
name = "ot-flyertalk-monitor"
version = "1.0.0"
description = "A script for monitoring flyertalk for new posts, and alerting the team."
authors = ["Josh Ourisman <josh@pingpong.travel>"]
license = "private"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.27.1"
beautifulsoup4 = "^4.11.1"
redis = "^4.2.2"
typer = "^0.4.1"
rich = "^12.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
