[tool.poetry]
name = "ot-flyertalk-monitor"
version = "2.0.0"
description = "A script for monitoring flyertalk for new posts, and alerting the team."
authors = ["Josh Ourisman <josh@pingpong.travel>"]
license = "private"

[tool.poetry.dependencies]
python = "~3.9"
requests = "^2.27.1"
beautifulsoup4 = "^4.11.1"
rich = "^12.2.0"
pydantic = "^1.9.0"
pendulum = "^2.1.2"
sqlmodel = "^0.0.6"

[tool.poetry.dev-dependencies]
redis = "^4.2.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
