name: Fetch latest thread data

on:
  repository_dispatch:
  schedule:
    - cron: "10 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Run monitor script
        run: |
          poetry install
          poetry run python monitor.py
      - name: Commit and push if there are new threads
        run: |
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest thread data: ${timestamp}" || exit 0
          git push
