name: Fetch latest thread data

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v3
        with:
          python-version: "3.9"
          cache: "poetry"
      - name: Install Dependencies
        run: poetry install
      - name: Run monitor script
        run: poetry run python monitor.py
      - name: Update database and deploy to Vercel if there are new threads
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          if ! git diff --quiet
          then
            git config user.name "Automated"
            git config user.email "actions@users.noreply.github.com"
            git add -A
            timestamp=$(date -u)
            git commit -m "Latest thread data: ${timestamp}" || exit 0
            git push
            poetry run datasette publish vercel threads.db --token $VERCEL_TOKEN --project ot-flyertalk-monitor
          fi
